### ISSUE TITLE
A real API is available

### ISSUE THREAD

**Issue by Incognito357** [ChrisMichaelPerezSantiago/crunchyrollapi#1]
I was trying to do something similar to what you were doing here, and found this: https://github.com/CloudMax94/crunchyroll-api/wiki

This repo explains enough of the public facing API to do everything I actually wanted to do and more.

I also came across this python repo which is based off the information from the first: https://github.com/buckley-w-david/crunchy-api

I figured I'd leave some links here, in case you're interested. For most, if not all of the API calls, you can also pass the locale as a parameter, and receive data in other languges (locale="esLA" for Spanish, for instance).

**Comment by chrismichaelps** [comment]
Hello @Incognito357 ,

Sure, you can use the API you want. Actually I could implement and do more with the API but time does not allow it.

I also don't think I can continue to maintain the API for time reasons
